# Tox (http://tox.testrun.org/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

[tox]
isolated_build = true
envlist = py310, py11, py12

[testenv]
allowlist_externals =
    /bin/cat
    /bin/cp
    /bin/mkdir
    /usr/bin/cat
    /usr/bin/cp
    /usr/bin/mkdir
    /usr/bin/git
    /usr/local/bin/git
    /opt/homebrew/bin/git
    poetry


[testenv:checkqa]
skip_install = True
deps = ruff
commands = ruff check

[testenv:run_tests]
deps =
    poetry
use_develop = True
commands =
    poetry install
    poetry run pytest {posargs}

####################
# Deployment tools #
####################

[testenv:bumpversion]
allowlist_externals =
    bump2version
     sh
    git
    echo

setenv =
    bump_part = {posargs:}
commands =
    sh -c 'current_version=$(bump2version --dry-run --list --allow-dirty {env:bump_part} | grep current_version= | sed -r s,"^.*=",,); \
    new_version=$(bump2version --dry-run --list --allow-dirty {env:bump_part} | grep new_version= | sed -r s,"^.*=",,); \
    commit_message="Bump version: ${current_version} → ${new_version}"; \
    bump2version {env:bump_part} --no-commit --no-tag ; \
    pre-commit run --all-files ; \
    git add .; \
    git commit -m "${commit_message}"'

skip_install = true
passenv = HOME
deps =
    bump2version

[testenv:build]
skip_install = false
deps =
    wheel
    build
commands =
    poetry build

[testenv:release]
skip_install = true
deps =
    bump2version

commands =
    bump2version release --tag
    git push --tags
    bump2version patch
    git push
allowlist_externals =
    /usr/bin/git
    /opt/homebrew/bin/git
